### ISSUE TITLE
Fix Typography on home page of website

### ISSUE THREAD

**Issue by manav1403** [RoboticsClubIITJ/web-portal#32]
File to be changed: [banner1](https://github.com/RoboticsClubIITJ/web-portal/blob/master/frontend/src/components/home/Banner1.vue)

**Comment by ddebrup** [comment]
There doesn't seem to exist any website pertaining to the given link.
Could you please verify and make sure if the link given is a correct one. Thanks.

**Comment by ddebrup** [comment]
> File to be changed: [banner1](frontend/src/components/home/Banner1.vue)

There doesn't seem to exist any website pertaining to the given link.
Could you please verify and make sure if the link given is a correct one. Thanks.

**Comment by manav1403** [comment]
@ddebrup sorry for that link is being updated now

**Comment by ddebrup** [comment]
> @ddebrup sorry for that link is being updated now

No problem, I am keeping the repo at watch. Thanks
