### ISSUE TITLE
Send Email to user when he registers for the first time on website

### ISSUE THREAD

**Issue by manav1403** [RoboticsClubIITJ/web-portal#33]
When the new user create his profile for the first time he should receive a welcome e-mail 

setup the local Gmail SMTP for the same

**Comment by ZeeshanAnwar15** [comment]
Improve docs

**Comment by manav1403** [comment]
@ZeeshanAnwar15 can you explain your staement

**Comment by harsh-ux** [comment]
@manav1403 can i work on this issue ?

**Comment by DarshitJain04** [comment]
> @manav1403 can i work on this issue ?

Yeah sure!

**Comment by manav1403** [comment]
we need to add an HTML template for the same also
@harsh-ux  di the same
