### ISSUE TITLE
Footer correction 

### ISSUE THREAD

**Issue by manav1403** [RoboticsClubIITJ/web-portal#35]
Reduce the size of ©2020 COPYRIGHT | Made with by Robotics WebD Team in the footer accordingly
its should be dynamic to mobile view as well.

**Comment by iamvaishnav** [comment]
I would like to work on this.

**Comment by manav1403** [comment]
yes @iamvaishnav  go ahead

**Comment by iamvaishnav** [comment]
Thanks @manav1403
