### ISSUE TITLE
Change the favicon and title

### ISSUE THREAD

**Issue by manav1403** [RoboticsClubIITJ/web-portal#37]
favicon ::
![robot](https://user-images.githubusercontent.com/51405571/94830649-6b948d80-0429-11eb-9630-10e4faadfc8b.png)

Title:: Robotics Club IITJ

**Comment by faisalgunanda** [comment]
i would like to work on this issue. can you assign this issue to me?

**Comment by faisalgunanda** [comment]
please check my PR sir
