### ISSUE TITLE
Adding menu items to the AppBar

### ISSUE THREAD

**Issue by manav1403** [RoboticsClubIITJ/web-portal#4]

**Comment by DarshitJain04** [comment]
Added menu items to AppBar

![Appbar](https://user-images.githubusercontent.com/56914284/89907297-1f3b8700-dc0a-11ea-9911-27945b11f8aa.jpg)

Appbar in normal view

![Appbar mobile-view](https://user-images.githubusercontent.com/56914284/89906974-ab00e380-dc09-11ea-8d8b-7011176273a6.jpg)

Menu items in drawer
