### ISSUE TITLE
Remove outline from buttons

### ISSUE THREAD

**Issue by samarth-1729** [RoboticsClubIITJ/web-portal#52]
## Issue
When some buttons get clicked black online forms around it, remove that outline 

## Description
For example on the Project page when you click on "Details", the Github link of any project a black outline forms around it

## Expected
No outline should form on clicking
![Screenshot](https://user-images.githubusercontent.com/59061958/95900164-1eaca180-0daf-11eb-979f-4848c0513b28.jpg)

**Comment by ikrydev** [comment]
i will work on this @DarshitJain04

**Comment by DarshitJain04** [comment]
> i will work on this @DarshitJain04 

Yeah, sure!
Assigning it to you

**Comment by DarshitJain04** [comment]
> ## Issue
> When some buttons get clicked black online forms around it, remove that outline
> 
> ## Description
> For example on the Project page when you click on "Details", the Github link of any project a black outline forms around it
> 
> ## Expected
> No outline should form on clicking
> ![Screenshot](https://user-images.githubusercontent.com/59061958/95900164-1eaca180-0daf-11eb-979f-4848c0513b28.jpg)

@ikrydev PS: This not only happens for the button, but also for the expansion panel
